version: "3"
services:
  angular:
    image: sandangel/angular-cli-docker:latest
    ports:
      - "4200:4200"
    command: ["ng", "serve", "-host", "0.0.0.0"]
    volumes:
      - .:/home/node
    working_dir: /home/node
